---
name: deploy

on:
  push:
    branches: ["main"]

env:
  CACHIX_CACHE: schnedo
  CARGO_TERM_COLOR: always

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: cache cargo packages
        uses: actions/cache@v5
        with:
          key: cargo-main-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            cargo-main-
          path: |
            ./target
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v16
        with:
          name: "${{ env.CACHIX_CACHE }}"
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Build
        run: nix build --no-update-lock-file --print-build-logs .
      - name: deploy
        run: cachix push "${{ env.CACHIX_CACHE }}" ./result
